### ISSUE TITLE
Cannot install MS Teams Plugin

### ISSUE THREAD

**Issue by schtho** [krfribeiro/check_mk#5]
Hi, 

I cannot install the MS Teams plugin.
The result:
<img width="1351" alt="Screen Shot 2022-10-01 at 16 41 05" src="https://user-images.githubusercontent.com/1516982/193414781-e613dfd0-eada-4491-a7ef-d4060ad91bec.png">

The used version of checkmk: Checkmk Enterprise 2.1.0p13.cee

Can you help me to solve this issue?
If you need any further assistance, please let me know.

**Comment by fhufenreuter** [comment]
We had the same issue. There is already a fix with commit https://github.com/krfribeiro/check_mk/commit/a82547202e280dc31d4f381f42e37ca38c2214b5 but a new package version is missing

**Comment by krfribeiro** [comment]
Hi @schtho and @fhufenreuter 
Can you try installing the 2.x version of the plugin and give me back if it got fixed ?
In checkmk exchange you have multiple versions of the package : 

![image](https://user-images.githubusercontent.com/6793264/198257337-3ee08e1b-a5b3-49bf-92cf-b79e68e0e574.png)

**Comment by fhufenreuter** [comment]
Hi @krfribeiro 
with the new Version it works now with 2.1.0p11
